### ISSUE TITLE
Mohit kumar

### ISSUE THREAD

**Issue by dbmohit** [arpit456jain/Wield-The-Web#11]
## Issue Type:

[ ] Bug Report
[ ] Feature Request
[ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by arpit456jain** [comment]
@dbmohit add your details in event.md file on your issue number and make PR
