### ISSUE TITLE
Vipul Jain

### ISSUE THREAD

**Issue by Vipuljain09** [arpit456jain/Wield-The-Web#28]
## Issue Type:

[ ] Bug Report
[ ] Feature Request
[ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by arpit456jain** [comment]
@Vipuljain09 add your details in event.md file on your issue number and make PR
