### ISSUE TITLE
Shivam Srivastava

### ISSUE THREAD

**Issue by Srivastava28** [arpit456jain/Wield-The-Web#36]
## Issue Type:

[ ] Bug Report
[ ] Feature Request
[ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by arpit456jain** [comment]
@Srivastava28 add your details in event.md file on your issue number and make PR
