### ISSUE TITLE
ABHIJEET SRIVASTAVA

### ISSUE THREAD

**Issue by abhijeet1312** [arpit456jain/Wield-The-Web#63]
## Issue Type:

[ ] Bug Report
[ ] Feature Request
[ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by arpit456jain** [comment]
@abhijeet1312 make a new PR there is some problem in previous one 

dont forget to fetch and merger and then  run git pull origin master
