### ISSUE TITLE
Harsh Prajapati

### ISSUE THREAD

**Issue by hash-party** [arpit456jain/Wield-The-Web#64]
## Issue Type:

[ ] Bug Report
[ ] Feature Request
[ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by arpit456jain** [comment]
hey @hash-party  make a PR and add your name and username in event.md file on your issue no
