### ISSUE TITLE
Abhay Singh

### ISSUE THREAD

**Issue by deltaTH** [arpit456jain/Wield-The-Web#91]
## Issue Type:

[ ] Bug Report
[ ] Feature Request
[ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by arpit456jain** [comment]
hey @deltaTH  please make a PR and add your name and username in event.md file on your issue no

**Comment by deltaTH** [comment]
sir 91 wale pe kal nhi ho rha tha toh maine nya issue create kar ke 92 pe kiya tha ....

**Comment by deltaTH** [comment]
91 pe phir try karte hai

**Comment by arpit456jain** [comment]
no @deltaTH its fine

**Comment by arpit456jain** [comment]
> sir 91 wale pe kal nhi ho rha tha toh maine nya issue create kar ke 92 pe kiya tha ....

ok @deltaTH got it your name is in the file great good job 
i am closing this issue
